// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2fe2A8soOfW-EXzdZ7V2nuW9rGEkE1nA',
    appId: '1:1015399295909:web:6aa6b8ba1bee581b4b164c',
    messagingSenderId: '1015399295909',
    projectId: 'x-physio',
    authDomain: 'x-physio.firebaseapp.com',
    storageBucket: 'x-physio.appspot.com',
    measurementId: 'G-W5DE3C4J7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6iMCBIPevdkt_-3SLqwkQfPLhL0w_IZE',
    appId: '1:1015399295909:android:ea3d51c944eea2ab4b164c',
    messagingSenderId: '1015399295909',
    projectId: 'x-physio',
    storageBucket: 'x-physio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzYo6HU8k32HmFdCeCIleib0nI14XqXUg',
    appId: '1:1015399295909:ios:dff36150ffd006384b164c',
    messagingSenderId: '1015399295909',
    projectId: 'x-physio',
    storageBucket: 'x-physio.appspot.com',
    iosClientId: '1015399295909-ba328mfdtj8t6gv8gscg8qs4llj5s4ii.apps.googleusercontent.com',
    iosBundleId: 'com.example.xphysio',
  );
}
